platform :ios, '11.2'

target 'web3swiftBrowser' do
  use_frameworks!
#  pod 'Alamofire', '~> 4.5'
#  pod 'BigInt', '~> 3.0.1'
  pod 'PromiseKit'
  pod 'AwaitKit'
#  pod 'PromiseKit/Alamofire', '~> 4.0'
#  pod 'CryptoSwift'
#  pod 'libsodium'
#  pod 'secp256k1_ios', '~> 0.0.6'
  pod 'web3swift'
  #pod 'web3swift', :path => '../web3swift/'
pod "WKBridge"
end
